version: '3'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: property-app
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    networks:
      - property-network

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: property-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - property-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: property-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: property_search
      MYSQL_USER: property_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - property-network

volumes:
  db_data:

networks:
  property-network:
    driver: bridge 